config/routes.rb
Brimir::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  resources :users do
    get :tickets, to: 'tickets#index'
  end

  namespace :tickets do
    resource :deleted, only: :destroy, controller: :deleted
    resource :selected, only: :update, controller: :selected
  end

  resources :tickets, except: [:destroy, :edit] do
    resource :lock, only: [:destroy, :create], module: :tickets
  end

  post "/:hook/:mail_key/tickets",
    controller: 'tickets',
    action: 'create',
    constraints: ->(r) { r.path_parameters[:hook].in? TicketsController::MAIL_HOOKS },
    format: :json

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :email_templates

  resources :labels, only: [:destroy, :update, :index, :edit]

  resources :replies, only: [:create, :new, :update, :show] do
    resource  :split_off, controller: 'tickets/split_off', only: [:create]
  end

  get '/attachments/:id/:format' => 'attachments#show'
  resources :attachments, only: [:index, :new]

  resources :email_addresses
  resources :email_imports, only: [:new, :create]

  resource :settings, only: [:edit, :update]

  root to: 'tickets#index'

  namespace :api do
    namespace :v1 do
      resources :email_templates, only: [ :show ]
      resources :tickets, only: [ :index, :show, :create ]
      resources :sessions, only: [ :create ]
      resources :users, param: :email, only: [ :create, :show ] do
        resources :tickets, only: [ :index ]
      end
    end
  end

end

app/models/reply.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# replies to tickets, made by a user, possibly with attachments
class Reply < ApplicationRecord
  include CreateFromUser
  include EmailMessage
  include ReplyNotifications
  prepend MergedReply

  attr_accessor :reply_to_id
  attr_accessor :reply_to_type

  validates :ticket_id, :content, presence: true

  belongs_to :ticket, touch: true
  belongs_to :user, optional: true

  accepts_nested_attributes_for :ticket

  scope :chronologically, -> { order(:created_at) }
  scope :with_message_id, lambda {
    where.not(message_id: nil)
  }

  scope :without_drafts, -> {
    where(draft: false)
  }

  scope :unlocked_for, ->(user) {
    joins(:ticket)
        .where('locked_by_id IN (?) OR locked_at < ?',
            [user.id, nil], Time.zone.now - 5.minutes)
  }

  scope :without_status_replies, -> {
    where.not(type: "StatusReply")
  }

  def reply_to
    reply_to_type.constantize.where(id: self.reply_to_id).first if reply_to_type
  end

  def reply_to=(value)
    self.reply_to_id = value.id
    self.reply_to_type = value.class.name
  end

  def other_replies
    ticket.replies.where.not(id: id)
  end

  def first?
    reply_to_type == 'Ticket'
  end

  def to_ticket
    Ticket.new(
      content: self.content,
      subject: self.ticket.subject,
      created_at: self.created_at,
      updated_at: self.updated_at,
      user_id: self.user_id,
      message_id: self.message_id,
      content_type: self.content_type,
      raw_message_file_name: self.raw_message_file_name,
      raw_message_content_type: self.raw_message_content_type,
      raw_message_file_size: self.raw_message_file_size,
      raw_message_updated_at: self.raw_message_updated_at,
      notified_user_ids: self.notified_user_ids,
      attachments: self.attachments.collect { |attachment|
        new_attachment = attachment.dup
        new_attachment.file = attachment.file
        new_attachment
      }
    )
  end
end

app/controllers/replies_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class RepliesController < ApplicationController
  include TimeHelper

  load_and_authorize_resource

  def new
    @users = User.actives
    @users = @users.agents if @reply.internal?
    @reply.assign_attributes(reply_params)
  end

  def create
    # store attributes and reopen ticket
    @reply = Reply.new({
        ticket_attributes: {
            status: 'open',
            id: reply_params[:ticket_id]
          }
    }.merge(reply_params.to_h))

    save_reply_and_redirect
  end

  def update
    @reply.assign_attributes(reply_params)
    save_reply_and_redirect
  end

  def show
    respond_to do |format|
      format.eml do
        begin
          send_file @reply.raw_message.path(:original),
              filename: "reply-#{@reply.id}.eml",
              type: 'text/plain',
              disposition: :attachment
        rescue => e
          print e.inspect
          raise ActiveRecord::RecordNotFound
        end
      end
    end
  end

  protected

  def save_reply_and_redirect
    if @reply.draft? && Tenant.current_tenant.share_drafts?
      @reply.user_id = nil
    else
      @reply.user_id = current_user.id
      @reply.created_at = Time.now
    end
    begin
      if @reply.draft?
        original_updated_at = @reply.ticket.updated_at

        @reply.save

        # don't screw up the ordering of inbox by resetting updated_at
        @reply.ticket.update_column :updated_at, original_updated_at

        redirect_to @reply.ticket, notice: I18n::translate(:draft_saved)
      else
        Reply.transaction do
          @reply.save!
          @reply.notification_mails.each(&:deliver_now)
        end

        redirect_to tickets_url, notice: I18n::translate(:reply_added)
      end
    rescue => e
      Rails.logger.error 'Exception occured on Reply transaction!'
      Rails.logger.error "Message: #{e.message}"
      Rails.logger.error "Backtrace: #{e.backtrace.join("\n")}"
      @outgoing_addresses = EmailAddress.verified.ordered
      @users = User.actives
      @users = @users.agents if @reply.internal?
      render 'new'
    end
  end

  def reply_params
    attributes = params.require(:reply).permit(
        :content,
        :ticket_id,
        :message_id,
        :user_id,
        :content_type,
        :draft,
        :internal,
        notified_user_ids: [],
        attachments_attributes: [
          :id,
          :_destroy,
          :file
        ],
        ticket_attributes: [
          :id,
          :to_email_address_id,
          :status,
        ]
    )

    unless can?(:update, Ticket.find(attributes[:ticket_id]))
      attributes.delete(:ticket_attributes)
    end

    attributes
  end

end

app/views/replies/_canned_replies.html.erb
<div data-canned-replies>
  <% options = options_for_select @canned_replies.map { |c| [c.name, api_v1_email_template_path(c)] } %>
  <%= select_tag nil, options, id: 'canned-reply', include_blank: true %>
</div>

app/views/replies/_form.html.erb
<%= form_for @reply, html: { multipart: true, class: 'new_reply' } do |r| %>
  <%= r.hidden_field :content_type, value: current_user.prefer_plain_text? ? 'text' : 'html' %>

  <%= r.hidden_field :ticket_id %>

  <div class="row collapse bb">
    <div class="medium-1 column ptl pll">
      <%= user_avatar current_user, class: 'avatar', size: 35 %>
    </div>
    <div class="medium-11 columns ptm pbm pll prl">
      <h3 class="text-default"><%= t(:reply) %></h3>
      <% if current_user.agent? %>
        <%= r.radio_button :internal, false, label: t(:reply), data: { remote: true, url: new_reply_path, params: "reply[ticket_id]=#{@reply.ticket.id}" } %>
        <%= r.radio_button :internal, true, label: t(:internal_note), data: { remote: true, url: new_reply_path, params: "reply[ticket_id]=#{@reply.ticket.id}" } %>
      <% end %>
      <% if can? :update, @reply.ticket %>
        <div class="row collapse">
          <%= r.fields_for :ticket do |f| %>
            <div class="medium-4 columns">
              <%= f.label :to_email_address_id, t('activerecord.attributes.reply.from'), class: 'ptm' %>
            </div>
            <div class="medium-8 columns">
              <% blank = @outgoing_addresses.count == 0 ? EmailAddress.default_email : '' %>
              <%= f.collection_select :to_email_address_id, @outgoing_addresses, :id, :formatted,
                  include_blank: blank, label: false %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="row collapse mbl">
        <div class="medium-4 columns">
          <label><%= t(:notification_will_be_sent_to) %></label>
        </div>
        <div class="medium-8 columns">
          <%= render 'replies/notified_users', r: r %>
        </div>
      </div>

      <% if (@canned_replies = EmailTemplate.canned_replies.order(:name)).any? %>
        <div class="row collapse mbl">
          <div class="medium-4 columns">
            <label><%= t(:canned_reply) %></label>
          </div>
          <div class="medium-8 columns">
            <%= render 'replies/canned_replies' %>
          </div>
        </div>
      <% end %>

      <%
        if @reply.content.blank? && @reply.errors.count == 0 # not on reply error view

          if current_user.prefer_plain_text?
            @reply.content = "\n#{html_to_text current_user.signature}\n"
          else
            @reply.content = "<p></p>#{current_user.signature}<br />"
          end

          if current_user.include_quote_in_reply?
            @reply.content += t(:on_date_author_wrote, author: @reply.reply_to.user.email,
                date: l(@reply.reply_to.created_at.in_time_zone(current_user.time_zone), format: :long))

            if current_user.prefer_plain_text?
              @reply.content += "\n#{wrap_and_quote(@reply.reply_to.content)}"
            else
              @reply.content += "<br />#{text_to_html(wrap_and_quote(@reply.reply_to.content))}"
            end
          end
        end
      %>

      <p>
      <% if current_user.prefer_plain_text? %>
        <%= r.text_area :content, label: false %>
      <% else %>
        <%= r.trix_editor :content, label: false %>
      <% end %>
      </p>

      <%= render 'attachments/form', f: r %>

      <% if can? :update, @reply.ticket %>
        <div class="row collapse">
          <%= r.fields_for :ticket do |f| %>
            <div class="medium-4 columns">
              <%= f.label :status, t(:change_status), class: 'ptm' %>
            </div>
            <div class="medium-8 columns">
              <%= f.collection_select(:status,
                  t('activerecord.attributes.ticket.statuses'), :first, :last,
                  label: false) %>
            </div>
          <% end %>
        </div>
      <% end %>

      <p>
        <%= r.button t(:save_as_draft), name: 'reply[draft]', value: true, class: 'button regular radius primary' %>

        <%= r.button @reply.internal? ? t(:attach_note) : t(:send_reply), name: 'reply[draft]', value: false, type: :submit, class: 'reply-submit button regular radius secondary' %>
      </p>

    </div>
  </div>
<% end %>

app/views/replies/_notified_users.html.erb
<div data-notified-users>
  <%= r.collection_select :notified_user_ids, @users.ordered, :id, :email, { label: false }, { multiple: true, class: 'select2' } %>
</div>

app/views/replies/_reply.html.erb
<ul class="accordion <%= 'internal-reply' if reply.internal? %> <%= 'status-reply' if reply.kind_of?(StatusReply) %>" data-accordion>
  <li class="accordion-navigation <%= div_class %>">
    <% if reply.is_a? SystemReply %>
      <a href="#reply-<%=reply.id%>" class="bb text-default">
        <div class="row collapse">
          <div class="medium-1 column pll">
            <%= system_gravatar class: 'avatar', size: 35 %>
          </div>
          <div class="medium-11 columns pll pts prl">
            <span><%= t(:reply_by) %> <strong><%= reply.ticket.reply_from_address %></strong></span>
            <span class="right" title="<%= l reply.created_at.in_time_zone(current_user.time_zone), format: :long %>">
              <i class="fa fa-clock-o"></i>
              <%= time_ago_as_phrase(reply.created_at.in_time_zone(current_user.time_zone)) %>
            </span>
          </div>
        </div>
      </a>
    <% else %>
      <a href="#reply-<%=reply.id%>" class="bb text-default">
        <div class="row collapse">
          <div class="medium-1 column pll">
            <%= user_avatar reply.user, class: 'avatar', size: 35 %>
          </div>
          <div class="medium-11 columns pll pts prl">
            <span><%= t(:reply_by) %> <strong><%= reply.user.email %></strong></span>
            <span class="right" title="<%= l reply.created_at.in_time_zone(current_user.time_zone), format: :long %>">
            <% if reply.attachments.count > 0 %>
              <i class="fa fa-paperclip"></i>
            <% end %>
              <i class="fa fa-clock-o"></i>
              <%= time_ago_as_phrase(reply.created_at.in_time_zone(current_user.time_zone)) %>
            </span>
          </div>
        </div>
      </a>
    <% end %>
    <div id="reply-<%=reply.id%>" class="content bb <%= div_class %>">

    <div class="row">
      <div class="medium-11 columns medium-push-1 mtl mbl">
        <% if reply.raw_message_file_size.to_i > 0 %>
          <a class="pull-right text-default" href="<%= reply_path(reply, format: :eml) %>"><%= fa_icon 'save' %></a>
        <% end %>

        <% if can?(:split_off, reply) && !reply.kind_of?(StatusReply) %>
          <%= link_to reply_split_off_path(reply_id: reply.id), method: 'post', class: 'pull-right text-default split-off-ticket' do %>
            <i class="fa fa-code-fork"></i>
            <%= t :split_off_ticket %>
          <% end %>
        <% end %>

        <% if reply.content_type == 'html' %>
          <% if reply.is_a? SystemReply %>
            <%= render('/shared/content_for_system_reply', reply: reply) %>
          <% else %>
            <%= sanitize_html(reply.content, reply.inline_files) %>
          <% end %>
        <% else %>
          <pre><%= word_wrap(html_to_text(reply.content), line_width: 72) %></pre>
        <% end %>

        <% if reply.attached_files.size > 0 %>
          <hr />
          <ul class="attachments">
            <%= render reply.attached_files %>
          </ul>
        <% end %>

        <hr />
        <%= render partial: 'shared/notified_users_list', locals: {reply: reply} %>
    </div>
  </li>
</ul>

app/views/replies/create.js.erb
window.location.reload();

app/views/replies/new.html.erb
<div class="row">
  <div class="medium-9 columns">

    <%= render 'form' %>

  </div>
</div>

app/views/replies/new.js.erb
<%
  result = ''
  form_for @reply do |r|
    result = render 'replies/notified_users', r: r
  end
%>

<% if @reply.internal? %>
  jQuery('iframe').contents().find('#tinymce').css('background-color', '#fff6d9');
  jQuery('#reply_content').css('background-color', '').css('background-color', '#fff6d9');
  jQuery('.reply-submit').text('<%= I18n.t(:attach_note) %>')
<% else %>
  jQuery('iframe').contents().find('#tinymce').css('background-color', '');
  jQuery('#reply_content').css('background-color', '');
  jQuery('.reply-submit').text('<%= I18n.t(:send_reply) %>')

<% end %>

jQuery('[data-notified-users]').html('<%= j result %>');
jQuery('[data-notified-users] select').select2({ width: 'resolve' });