config/routes.rb
Brimir::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  resources :users do
    get :tickets, to: 'tickets#index'
  end

  namespace :tickets do
    resource :deleted, only: :destroy, controller: :deleted
    resource :selected, only: :update, controller: :selected
  end

  resources :tickets, except: [:destroy, :edit] do
    resource :lock, only: [:destroy, :create], module: :tickets
  end

  post "/:hook/:mail_key/tickets",
    controller: 'tickets',
    action: 'create',
    constraints: ->(r) { r.path_parameters[:hook].in? TicketsController::MAIL_HOOKS },
    format: :json

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :email_templates

  resources :labels, only: [:destroy, :update, :index, :edit]

  resources :replies, only: [:create, :new, :update, :show] do
    resource  :split_off, controller: 'tickets/split_off', only: [:create]
  end

  get '/attachments/:id/:format' => 'attachments#show'
  resources :attachments, only: [:index, :new]

  resources :email_addresses
  resources :email_imports, only: [:new, :create]

  resource :settings, only: [:edit, :update]

  root to: 'tickets#index'

  namespace :api do
    namespace :v1 do
      resources :email_templates, only: [ :show ]
      resources :tickets, only: [ :index, :show, :create ]
      resources :sessions, only: [ :create ]
      resources :users, param: :email, only: [ :create, :show ] do
        resources :tickets, only: [ :index ]
      end
    end
  end

end

app/models/label.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# labels attached via labelings to users or tickets
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :users, through: :labelings, source: :labelable, source_type: 'User'

  after_initialize :assign_random_color

  COLORS = [
    '#de6262',
    '#65a8dd',
    '#6fc681',
    '#9d61dd',
    '#6370dd',
    '#dca761',
    '#a86f72',
    '#759d91',
    '#727274'
  ]

  scope :ordered, lambda {
    order(:name)
  }

  scope :viewable_by, lambda { |user|
    if !user.agent? || user.labelings.count > 0
      where(id: user.label_ids)
    end
  }

  def assign_random_color
    self.color = Label::COLORS.sample if color.blank?
  end
end

app/controllers/labels_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class LabelsController < ApplicationController

  load_and_authorize_resource :label

  def destroy
    @label.destroy

    respond_to :js
  end

  def update

    if params[:label].present? && params[:label][:name].present?
      @label.name = params[:label][:name]
    elsif params[:color].present?
      @label.color = Label::COLORS[ params[:color].to_i % Label::COLORS.count ]
    end

    @label.save

    respond_to :js
  end

  def edit
    respond_to :js
  end

  def index
    @labels = Label.viewable_by(current_user).where('name LIKE ?', "#{params[:q]}%")
    respond_to :json
  end

end

app/views/labels/_form.html.erb
<%= form_for @label, html: { class: 'clearfix' }, remote: true do |f| %>
  <%= f.text_field :name, label: false, class: 'no-m' %>
  
  <%= link_to label_path(@label), data: { method: :put, remote: true } do %>
    <i class="fa fa-close"></i>
  <% end %>

  <button type="submit"><i class="fa fa-check"></i></button>

<% end %>

app/views/labels/_label.html.erb
<span style="background: <%= label.color %>" class="radius label" data-label-id="<%= label.id %>"><%= label.name %></span>

app/views/labels/_label_li.html.erb
<%
  # toggle label on/off
  if params[:label_id].to_i == label.id
    p = permitted_params.merge({ label_id: nil })
  else
    p = permitted_params.merge({ label_id: label.id })
  end
%>
<li data-edit-label-row="<%= label.id %>">
  <a href="<%= tickets_url(p) %>" class="<%= 'active ' if params[:label_id].to_i == label.id %>hover-icon-a">
    <span class="pas ib mrl" style="background-color: <%= label.color %>"></span>
    <%= label.name %>
    <i data-dropdown="label-<%= label.id %>" class="fa fa-toggle-down hover-icon-i"></i>
  </a>
  <ul id="label-<%= label.id %>" class="f-dropdown medium-block-grid-3" data-dropdown-content>
    <% Label::COLORS.each_with_index do |color, index| %>
      <li>
        <%= link_to label_path(label, color: index), method: :patch, remote: true do %>
          <span class="pas ib" style="background-color: <%= color %>"></span>
        <% end %>
      </li>
    <% end %>
    <li>
      <%= link_to label_path(label), method: :delete, data: { confirm: t(:are_you_sure) }, remote: true do %>
        <%= fa_icon 'trash' %>
      <% end %>
    </li>
    <li>
      <%= link_to edit_label_path(label), remote: true do %>
        <%= fa_icon 'edit' %>
      <% end %>
    </li>
  </ul>
</li>

app/views/labels/destroy.js.erb
jQuery('[data-label-id="<%= @label.id %>"]').fadeOut();
jQuery('[data-dropdown="label-<%= @label.id %>"]').closest('li').fadeOut();

app/views/labels/edit.js.erb
jQuery('[data-edit-label-row="<%= @label.id %>"]').html("<%= j render 'form' %>");

app/views/labels/update.js.erb
jQuery('[data-label-id="<%= @label.id %>"]').css('background', '<%= @label.color %>');
jQuery('[data-label-id="<%= @label.id %>"]').html('<%= @label.name %>');

jQuery('[data-dropdown="label-<%= @label.id %>"]').closest('a').find('span').css('background-color', '<%= @label.color %>');
jQuery('[data-dropdown="label-<%= @label.id %>"]').closest('a').find('span').html('<%= @label.name %>');

jQuery('[data-edit-label-row="<%= @label.id %>"]').replaceWith("<%= j render 'label_li', label: @label %>");

<%# close all dropdowns %>
var dropdowns = jQuery('.f-dropdown');
dropdowns.foundation('dropdown', 'close', dropdowns);