config/routes.rb
Brimir::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  resources :users do
    get :tickets, to: 'tickets#index'
  end

  namespace :tickets do
    resource :deleted, only: :destroy, controller: :deleted
    resource :selected, only: :update, controller: :selected
  end

  resources :tickets, except: [:destroy, :edit] do
    resource :lock, only: [:destroy, :create], module: :tickets
  end

  post "/:hook/:mail_key/tickets",
    controller: 'tickets',
    action: 'create',
    constraints: ->(r) { r.path_parameters[:hook].in? TicketsController::MAIL_HOOKS },
    format: :json

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :email_templates

  resources :labels, only: [:destroy, :update, :index, :edit]

  resources :replies, only: [:create, :new, :update, :show] do
    resource  :split_off, controller: 'tickets/split_off', only: [:create]
  end

  get '/attachments/:id/:format' => 'attachments#show'
  resources :attachments, only: [:index, :new]

  resources :email_addresses
  resources :email_imports, only: [:new, :create]

  resource :settings, only: [:edit, :update]

  root to: 'tickets#index'

  namespace :api do
    namespace :v1 do
      resources :email_templates, only: [ :show ]
      resources :tickets, only: [ :index, :show, :create ]
      resources :sessions, only: [ :create ]
      resources :users, param: :email, only: [ :create, :show ] do
        resources :tickets, only: [ :index ]
      end
    end
  end

end

app/models/user.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class User < ApplicationRecord
  devise Rails.application.config.devise_authentication_strategy, :recoverable,
    :rememberable, :trackable, :validatable,:omniauthable,
    omniauth_providers: [:google_oauth2]

  has_many :tickets, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :labelings, as: :labelable, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :assigned_tickets, class_name: 'Ticket',
      foreign_key: 'assignee_id', dependent: :nullify
  has_many :notifications, dependent: :destroy

  belongs_to :schedule, optional: true

  # identities for omniaut
  has_many :identitie

  has_and_belongs_to_many :unread_tickets, class_name: 'Ticket'

  after_initialize :default_localization
  before_validation :generate_password

  accepts_nested_attributes_for :schedule

  # All ldap users are agents by default, remove/comment this method if this
  # is not the intended behavior.
  def ldap_before_save
    self.agent = true
  end

  scope :actives, -> {
    where(active: true)
  }

  scope :inactives, -> {
    where(active: false)
  }

  scope :agents, -> {
    where(agent: true)
  }

  scope :by_agent, ->(value) {
    where(agent: value)
  }

  scope :ordered, -> {
    order(:email)
  }

  scope :by_email, ->(email) {
    where('LOWER(email) LIKE ?', '%' + email.downcase + '%')
  }

  scope :search, ->(term) {
    if !term.nil?
      term.gsub!(/[\\%_]/) { |m| "!#{m}" }
      term = "%#{term.downcase}%"
      where('LOWER(email) LIKE ? ESCAPE ?', term, '!')
    end
  }

  def name
    super || name_from_email_address
  end

  def locale
    (super.blank? ? Rails.configuration.i18n.default_locale : super).to_sym
  end

  def is_working?
    #sanity checks for default behaviour
    return true unless schedule_enabled # this is the default behaviour
    return true if schedule.nil? # this is the default behaviour
    schedule.is_during_work?(Time.now.in_time_zone(self.time_zone))
  end

  def name_from_email_address
    email.split('@').first
  end

  # notify only active agents
  def self.agents_to_notify
    User.agents
        .where(notify: true).actives
  end

  # Does the email address of this user belong to the ticket system
  # itself? For example, there might be a user corresponding to
  # support@example.com.
  #
  # This check is needed to prevent email loops. We do not want to
  # deliver to those email addresses, since they would be received
  # by the ticket system, again, creating an email loop.
  #
  def ticket_system_address?
    User.ticket_system_addresses.pluck(:id).include? self.id
  end

  # Return all users that correspond to email addresses belonging
  # to the ticket system, e.g. support@example.com.
  #
  def self.ticket_system_addresses
    User.where(email: EmailAddress.pluck(:email))
  end

  def client?
    not agent?
  end

  def default_localization
    self.time_zone = Tenant.current_tenant.default_time_zone if time_zone.blank?
    self.locale = Tenant.current_tenant.default_locale if locale.blank?
  end

  def generate_password
    if encrypted_password.blank?
      self.password = Devise.friendly_token.first(12)
    end
  end

  def active_for_authentication?
      super and self.active
  end
end

app/controllers/api/v1/users_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
class Api::V1::UsersController < Api::V1::ApplicationController
  include UsersStrongParams
  load_and_authorize_resource :user

  def create
    @user = User.new(user_params)
    if @user.save
      head :created
    else
      head :bad_request
    end
  end

  def show
    unless @user = User.find_by(email: Base64.urlsafe_decode64(params[:email]))
      head :bad_request
    end
  end
end

app/controllers/users_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class UsersController < ApplicationController
  include UsersStrongParams

  load_and_authorize_resource :user

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    # if no password was posted, remove from params
    if params[:user][:password] == ''
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if current_user == @user
      params[:user].delete(:agent) # prevent removing own agent permissions
    end

    if @user.update_attributes(user_params)

      if current_user.agent? && current_user.labelings.count == 0
        redirect_to users_url, notice: I18n.translate(:settings_saved)
      else
        redirect_to tickets_url, notice: I18n.translate(:settings_saved)
      end

    else
      render action: 'edit'
    end
  end

  def index
    @users = User.ordered.paginate(page: params[:page])
    @users = @users.actives.search(params[:q]) if params[:active].blank?
    @users = @users.inactives.search(params[:q]) unless params[:active].blank?
    @users = @users.by_agent(params[:agent] == '1') unless params[:agent].blank?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      user_welcome_mailer
      redirect_to users_url, notice: I18n.translate(:user_added)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: I18n.translate(:user_removed)
  end

  protected

  def user_welcome_mailer
    template = EmailTemplate.by_kind('user_welcome').active.first
    tenant = Tenant.current_tenant
    if !template.nil?
      NotificationMailer.new_account(@user, template, tenant).deliver_now
    end
  end
end

app/helpers/user_helper.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2015 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# helpers used for EmailTemplate views
module UserHelper
  def build_schedule_for_user
    # sanity check
    return if @user.nil?

    @user.schedule ||= @user.build_schedule

    # we need this
    @user.schedule
  end

  def localize_day_name(weekday)
    t('date.day_names')[weekday].downcase
  end

end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: 'edit_user'} do |f| %>
    <div class="row mt mb">

      <div class="medium-6 columns">

        <h5><%= t(:account_settings) %></h5>

        <p><%= t(:only_fill_in_passwords_when_modifying) %></p>

        <% if can? :create, User %>
            <%= f.text_field :email, tabindex: tabindex %>
        <% end %>

        <%= f.text_field :name, tabindex: tabindex %>

        <%= f.password_field :password, tabindex: tabindex %>

        <%= f.password_field :password_confirmation, tabindex: tabindex %>

        <% if can? :create, User %>
            <%= f.check_box :agent, label: t(:user_is_an_agent), tabindex: tabindex %>
        <% end %>

        <%= f.check_box :active, label: t(:active), tabindex: tabindex %>

        <%= f.select :time_zone, @time_zones, {}, tabindex: tabindex %>

        <%= f.select :locale, @locales, {}, tabindex: tabindex %>

        <%= f.select :per_page, [10, 20, 30, 50, 75, 100], {}, tabindex: tabindex %>

      </div>

      <div class="medium-6 columns">

        <% if @user.agent? %>

          <h5><%= t(:notification_settings) %></h5>

          <label>
            <%= f.radio_button :schedule_enabled, false, label: false %>
            <%= t('activerecord.attributes.user.schedule_enabled_false') %>
          </label>

          <label>
            <%= f.radio_button :schedule_enabled, true, label: false %>
            <%= t('activerecord.attributes.user.schedule_enabled_true') %>
          </label>

          <div data-work-can-wait style="<%= @user.schedule_enabled? ?
              'display: block;' : 'display: none;' %>">
            <%= f.fields_for :schedule, build_schedule_for_user do |ff|  %>
              <div class="row">
                <div class="small-5 medium-4 large-3 columns">
                  <%
                    selected = '8:00'
                    unless ff.object.start.nil?
                      selected = "#{ff.object.start.hour}:00"
                    end
                  %>
                  <%= ff.select :start,
                      options_for_select((0..23).map { |n| "#{n}:00" }, selected),
                      label: false %>
                </div>
                <div class="small-2 medium-2 large-1 column">
                  <label class="inline text-center">
                    <%= t(:until) %>
                  </label>
                </div>
                <div class="small-5 medium-4 large-3 columns end">
                  <%
                    selected = '18:00'
                    unless ff.object.end.nil?
                      selected = "#{ff.object.end.hour}:00"
                    end
                  %>
                  <%= ff.select :end,
                      options_for_select((0..23).map { |n| "#{n}:00" }, selected),
                      label: false %>
                </div>
              </div>
              <label class="checkbox-helper">
                <%= ff.check_box :sunday, label: false %>
                <span><%= localize_day_name(0).first(2) %></span>
              </label>
              <label class="checkbox-helper">
                <%= ff.check_box :monday, label: false %>
                <span><%= localize_day_name(1).first(2) %></span>
              </label>
              <label class="checkbox-helper">
                <%= ff.check_box :tuesday, label: false %>
                <span><%= localize_day_name(2).first(2) %></span>
              </label>
              <label class="checkbox-helper">
                <%= ff.check_box :wednesday, label: false %>
                <span><%= localize_day_name(3).first(2) %></span>
              </label>
              <label class="checkbox-helper">
                <%= ff.check_box :thursday, label: false %>
                <span><%= localize_day_name(4).first(2) %></span>
              </label>
              <label class="checkbox-helper">
                <%= ff.check_box :friday, label: false %>
                <span><%= localize_day_name(5).first(2) %></span>
              </label>
              <label class="checkbox-helper">
                <%= ff.check_box :saturday, label: false %>
                <span><%= localize_day_name(6).first(2) %></span>
              </label>
            <% end %>
          </div>
        <% end %>

        <h5><%= t(:email_settings) %></h5>

        <%= f.check_box :prefer_plain_text, tabindex: tabindex %>
        <%= f.check_box :include_quote_in_reply, tabindex: tabindex %>

        <% if @user.agent? %>

          <%= f.check_box :notify,
              label: t(:receive_new_ticket_notifications), tabindex: tabindex %>

          <h5><%= t(:signature) %></h5>
          <%= f.trix_editor :signature, class: 'mbl', tabindex: tabindex %>
        <% end %>

        <% if can? :create, Labeling.new(labelable: @user) %>
          <h5><%= t(:access_control) %></h5>

          <p><%= t(:have_access_to_label) %></p>

          <%= f.collection_select :label_ids, @labels, :id, :name, {}, {
              multiple: true, class: 'select2 mbl', tabindex: tabindex } %>
        <% end %>

        <% unless Rails.application.secrets[:google_client_id].blank? %>

          <h5><%= t(:omniauth_connect_title) %></h5>

          <p><%= t(:omniauth_connect_text) %></p>

          <%= link_to user_google_oauth2_omniauth_authorize_path do %>
            <i class="fa fa-google-plus-square"></i>
            <%= t(:omniauth_connect_google_text) %>
          <% end %>

        <% end %>

      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns bt">
        <%= f.submit t(:save), class: 'success button radius mtl' %>
      </div>
    </div>

<% end %>

app/views/users/edit.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-6 columns">
      <h4 class="no-m pts pbs"><%= t(:edit_user) %></h4>
    </div>
    <div class="medium-6 columns">
      <% if can? :destroy, @user %>
        <%= link_to t(:remove_user), user_path(@user), 
            method: :delete, 
            data: { confirm: t(:are_you_sure) },
            class: 'no-m radius right tiny button' %>
      <% end %>
    </div>
  </div>
</div>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="panel pam no-bt">
  <div class="row collapse">
    <div class="medium-12 columns">
      <div class="row collapse">
        <div class="medium-3 columns">
          <h3 class="filter-title no-m pts plm"><%= t(:users) %></h3>
        </div>
        <div class="medium-9 columns">
          <%= form_tag users_path, method: :get, class: 'prm' do %>

            <div class="row collapse">

              <%= link_to new_user_path, class: 'radius tiny button right mlm no-m' do %>
                <i class="fa fa-plus" style="top:1px"></i>
              <% end %>

              <div class="small-2 columns right">
                <%= button_tag '<i class="fa fa-search"></i>'.html_safe, type: 'submit', class: 'secondary radius no-bl no-m button postfix' %>
              </div>
              <div class="small-5 columns right">
                <%= text_field_tag :q, params[:q], class: 'no-m radius-tl radius-bl' %>
              </div>

              <label class="ib mts"><%= check_box_tag :active, 0, params[:active] %><%= t(:inactive) %></label>
              <label class="ib mts mll mrl pull-right"><%= radio_button_tag :agent, 0, params[:agent] == '0' %> <%= t(:customer) %></label>
              <label class="ib mts pull-right"><%= radio_button_tag :agent, 1, params[:agent] == '1' %> <%= t(:agent) %></label>

            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<table class="full">
  <thead>
    <tr>
      <th><%= t(:email) %></th>
      <th><%= User.human_attribute_name(:name) -%></th>
      <th><%= t(:role) %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user_avatar user, class: 'avatar' %>
          <%= link_to user.email, edit_user_path(user) %>
        </td>
        <td><%= user.name -%></td>
        <td><%= (user.agent?) ? t(:agent) : t(:customer) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination-centered">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-12 columns">
      <h4 class="no-m pts pbs"><%= t(:new_user) %></h4>
    </div>
  </div>
</div>
<%= render 'form' %>