config/routes.rb
Brimir::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }

  resources :users do
    get :tickets, to: 'tickets#index'
  end

  namespace :tickets do
    resource :deleted, only: :destroy, controller: :deleted
    resource :selected, only: :update, controller: :selected
  end

  resources :tickets, except: [:destroy, :edit] do
    resource :lock, only: [:destroy, :create], module: :tickets
  end

  post "/:hook/:mail_key/tickets",
    controller: 'tickets',
    action: 'create',
    constraints: ->(r) { r.path_parameters[:hook].in? TicketsController::MAIL_HOOKS },
    format: :json

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :email_templates

  resources :labels, only: [:destroy, :update, :index, :edit]

  resources :replies, only: [:create, :new, :update, :show] do
    resource  :split_off, controller: 'tickets/split_off', only: [:create]
  end

  get '/attachments/:id/:format' => 'attachments#show'
  resources :attachments, only: [:index, :new]

  resources :email_addresses
  resources :email_imports, only: [:new, :create]

  resource :settings, only: [:edit, :update]

  root to: 'tickets#index'

  namespace :api do
    namespace :v1 do
      resources :email_templates, only: [ :show ]
      resources :tickets, only: [ :index, :show, :create ]
      resources :sessions, only: [ :create ]
      resources :users, param: :email, only: [ :create, :show ] do
        resources :tickets, only: [ :index ]
      end
    end
  end

end

app/models/rule.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# filter rules applied to a ticket when it is created
class Rule < ApplicationRecord
  validates :filter_field, presence: true

  enum filter_operation: [:contains, :equals]
  enum action_operation: [:assign_label, :notify_user, :change_status,
                          :change_priority, :assign_user]

  def filter(ticket)
    if ticket.respond_to?(filter_field)
      value = ticket.send(filter_field).to_s
    else
      value = ticket.attributes[filter_field].to_s
    end

    if filter_operation == 'contains'
      value.downcase.include?(filter_value.downcase)
    elsif filter_operation == 'equals'
      value.downcase == filter_value.downcase
    end
  end

  def execute(ticket)
    if action_operation == 'assign_label'
      label = Label.where(name: action_value).first_or_create
      ticket.labels << label unless ticket.labels.include?(label)

    elsif action_operation == 'notify_user'
      user = User.where(email: action_value.downcase.strip).first_or_create

      if !user.nil? && !ticket.notified_users.include?(user)
        ticket.notified_users << user
      end

    elsif action_operation == 'change_status'
      ticket.status = action_value.downcase
      ticket.save

    elsif action_operation == 'change_priority'
      ticket.priority = action_value.downcase
      ticket.save

    elsif action_operation == 'assign_user'
      user = User.where(email: action_value).first

      unless user.nil?
        ticket.assignee = user
        ticket.save
      end

    end
  end

  def self.apply_all(ticket)
    Rule.all.each do |rule|
      rule.execute(ticket) if rule.filter(ticket)
    end
  end
end

app/controllers/rules_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2016 Ivaldi https://ivaldi.nl/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class RulesController < ApplicationController

  load_and_authorize_resource :rule

  before_action :load_resources

  def index
    @rules = @rules.paginate(page: params[:page])
  end

  def new
  end

  def create
    @rule = Rule.new(rule_params)

    if @rule.save
      redirect_to rules_url, notice: t(:rule_added)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @rule.update_attributes(rule_params)
      redirect_to rules_url, notice: t(:rule_modified)
    else
      render 'edit'
    end
  end

  def destroy
    @rule.destroy

    redirect_to rules_url, notice: t(:rule_deleted)
  end

  protected
    def rule_params
      params.require(:rule).permit(
          :filter_field,
          :filter_operation,
          :filter_value,
          :action_operation,
          :action_value,
      )
    end

    def load_resources
      @label_options = Label.ordered.map do |l|
        {
          key: l.name,
          value: l.name,
        }
      end
      @users = User.agents.ordered.map do |u|
        {
          key: u.email,
          value: u.email
        }
      end
      @statuses = Ticket.statuses.except(:merged).map do |s,i|
        {
          key: s,
          value: t(s, scope: 'activerecord.attributes.ticket.statuses')
        }
      end
      @priorities = Ticket.priorities.map do |p,i|
        {
          key: p,
          value: t(p)
        }
      end
    end

end

app/views/rules/_form.html.erb
<%= form_for @rule do |f| %>
  <div class="row mt mb">
    <div class="large-6 columns">
      <%
        fields = []
        [:from, :subject, :content, :orig_to, :orig_cc, :to].each do |key|
          fields << [t(key, scope: 'activerecord.attributes.ticket'), key]
        end
      %>
      <%= f.select(:filter_field, fields) %>

      <%= f.collection_select(:filter_operation, t('activerecord.attributes.rule.filter_operations'), :first, :last) %>

      <%= f.text_field :filter_value %>

      <%= react_component('RuleFields', {
          actions: {
            assign_label: {
              label: t('activerecord.attributes.rule.action_operations.assign_label'),
              values: @label_options
            },
            assign_user: {
              label: t('activerecord.attributes.rule.action_operations.assign_user'),
              values: @users
            },
            change_status: {
              label: t('activerecord.attributes.rule.action_operations.change_status'),
              values: @statuses
            },
            change_priority: {
              label: t('activerecord.attributes.rule.action_operations.change_priority'),
              values: @priorities
            },
            notify_user: {
              label: t('activerecord.attributes.rule.action_operations.notify_user'),
              values: @users
            }
          },
          label_action_operation: t('activerecord.attributes.rule.action_operation'),
          action_operation: f.object.action_operation,
          action_value: f.object.action_value
      }) %>
    </div>
  </div>

  <div class="row">
    <div class="medium-12 columns bt">
      <%= f.submit t(:save), class: 'success button radius mtl' %>
    </div>
  </div>
<% end %>

app/views/rules/edit.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-6 columns">
      <h4 class="no-m pts pbs"><%= t(:edit_rule) %></h4>
    </div>
    <div class="medium-6 columns">
      <%= link_to t(:delete_rule), rule_path(@rule), 
          method: :delete, 
          data: { confirm: t(:are_you_sure) },
          class: 'no-m radius right tiny button' %>
    </div>
  </div>
</div>
<%= render 'form' %>

app/views/rules/index.html.erb
<div class="panel no-bt">
  <div class="row collapse">
    <div class="medium-6 columns">
      <h4 class="no-m pts pbs"><%= t(:rules) %></h4>
    </div>
    <div class="medium-6 columns">
      <%= link_to t(:new_rule), new_rule_path, class: 'no-m tiny button right radius' %>
    </div>
  </div>
</div>

<div class="row collapse">
  <div class="large-12 columns">

    <table class="full">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.rule.filter_field') %></th>
          <th><%= t('activerecord.attributes.rule.filter_operation') %></th>
          <th><%= t('activerecord.attributes.rule.filter_value') %></th>
          <th><%= t('activerecord.attributes.rule.action_operation') %></th>
          <th><%= t('activerecord.attributes.rule.action_value') %></th>
        </tr>
      </thead>
      <tbody>
        <% @rules.each do |rule| %>
          <tr>
            <td><%= link_to t(rule.filter_field, scope: 'activerecord.attributes.ticket'), edit_rule_path(rule) %></td>
            <td><%= t(rule.filter_operation, scope: 'activerecord.attributes.rule.filter_operations') %></td>
            <td><%= rule.filter_value %></td>
            <td><%= t(rule.action_operation, scope: 'activerecord.attributes.rule.action_operations') %></td>
            <td><%= rule.action_value %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="pagination-centered">
      <%= will_paginate @rules %>
    </div>
  </div>
</div>

app/views/rules/new.html.erb
<div class="panel no-bt mbl">
  <div class="row collapse">
    <div class="medium-12 columns">
      <h4 class="no-m pts pbs"><%= t(:new_rule) %></h4>
    </div>
  </div>
</div>
<%= render 'form' %>